default:
   adapter: postgresql
   database: scvsoft
   username: postgres
   password: Oso10rojo
   host: 34.71.137.173
   port: 5432
development:
   adapter: postgresql
   database: scvsoft
   username: postgres
   password: Oso10rojo
   host: 34.71.137.173
   port: 5432
test:
   adapter: postgresql
   database: scvsoft
   username: postgres
   password: Oso10rojo
   host: 34.71.137.173
   port: 5432
production:
   adapter: postgresql
   database: scvsoft
   username: postgres
   password: Oso10rojo
   host: 34.71.137.173
   port: 5432