CREATE TABLE RECETA (
	ID numeric(19,0) NOT NULL PRIMARY KEY,
	NOMBRE character varying(255) NOT NULL,
	VALORACION numeric(4,2),
	FECHA_CREACION TIMESTAMP NOT NULL default NOW()
);
CREATE SEQUENCE RECETA_ID_SEQ;
ALTER TABLE RECETA ALTER ID SET DEFAULT NEXTVAL('RECETA_ID_SEQ');

ALTER TABLE public.receta ADD PORCIONES numeric(4) NULL;