CREATE TABLE INGREDIENTE (
	ID NUMERIC (19,0) NOT NULL PRIMARY KEY,
	NOMBRE CHARACTER VARYING(255) NOT NULL
);

CREATE SEQUENCE INGREDIENTE_ID_SEQ;
ALTER TABLE INGREDIENTE ALTER ID SET DEFAULT NEXTVAL('INGREDIENTE_ID_SEQ');
ALTER TABLE public.ingrediente ADD unidad varchar(255) NULL;