CREATE table RECETA_INGREDIENTE (
	ID_RECETA numeric (19,0) NOT NULL REFERENCES RECETA,
	ID_INGREDIENTE numeric (19,0) NOT NULL REFERENCES INGREDIENTE,
	CANTIDAD character varying(255) NOT NULL,
	PRIMARY KEY (ID_RECETA, ID_INGREDIENTE)
);